# ~/.config/alacritty/keybinds.toml

[keyboard]
bindings = [

# copy selection to clipboard, ctrl+y
{ key = "Y", mods = "Control", action = "Copy" },

# paste into terminal from clipboard, ctrl+p
{ key = "P", mods = "Control", action = "Paste" },


# increase/decrease/reset font size, ctrl++/ctrl+-/ctrl+#
{ key = "+", mods = "Control", action = "IncreaseFontSize" },
{ key = "-", mods = "Control", action = "DecreaseFontSize" },
{ key = "#", mods = "Control", action = "ResetFontSize" },



]
